### ISSUE TITLE
Simple main to compare two directories

### ISSUE THREAD

**Issue by victornoel** [hadii-tech/striff-lib#7]
Hi, I'm very excited about striff, this could really change the way we do reviews :)

Is there any plan to have a simple main to which you can give 2 directories and it will generate the striff diagrams ready to be opened with an image viewer?

**Comment by Zir0-93** [comment]
Hi, this is a great idea. I will start working on adding a simple entry point to the diagram generation process using two directories like you mentioned.

I also think the README should better explain alternative processes for supplying code to generate striffs, I will do this as well.

**Comment by victornoel** [comment]
very nice, thx @Zir0-93!
